version: 2

sources:
  - name: ebay_raw_source
    database: EBAY_ANALYTICS
    schema: RAW
    tables:
      - name: EBAY_RAW
        columns:
          - name: ITEM_ID
            tests:
              - not_null

snapshots:
  - name: snap_seller
    description: "Snapshot for tracking changes to seller attributes (Type 2 SCD)"
    columns:
      - name: seller_username_cleaned
        description: "Natural key for identifying the seller"
        tests:
          - not_null
      - name: seller_feedback_score
        description: "Seller's feedback score"
      - name: seller_feedback_percentage
        description: "Seller's positive feedback percentage"
      - name: load_timestamp
        description: "When the record was extracted from the source"

models:
  - name: stg_ebay_items
    description: "Flattened source of eBay item listings"
    columns:
      - name: item_id
        tests: [not_null, unique]
      - name: title
      - name: condition
      - name: condition_id
      - name: category_id
      - name: category_name
      - name: seller_username
      - name: seller_username_cleaned
      - name: seller_feedback_percentage
      - name: seller_feedback_score
      - name: listing_marketplace_id
      - name: item_location_country
      - name: price_value
      - name: price_currency
      - name: adult_only
      - name: available_coupons
      - name: top_rated_buying_experience
      - name: priority_listing
      - name: item_origin_date
      - name: item_creation_date
      - name: load_timestamp

  - name: fact_item_listing
    description: "Fact table with one row per item listing"
    columns:
      - name: item_listing_sk
        tests: [not_null, unique]
      - name: item_id
        tests: [not_null]
      - name: title
      - name: condition_sk
        tests:
          - relationships:
              to: ref('dim_condition')
              field: condition_sk
      - name: category_sk
        tests:
          - relationships:
              to: ref('dim_category')
              field: category_sk
      - name: seller_sk
      - name: origin_date_sk
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_sk
      - name: creation_date_sk
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_sk
      - name: load_date_sk
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_sk
      - name: marketplace_id
      - name: item_location_country
      - name: price_value
      - name: price_currency
      - name: adult_only
      - name: available_coupons
      - name: top_rated_buying_experience
      - name: priority_listing
  #DIMS
  - name: dim_condition
    description: "Condition dimension with surrogate key"
    columns:
      - name: condition_sk
        tests: [not_null, unique]
      - name: condition_id
      - name: condition

  - name: dim_category
    description: "Leaf category dimension"
    columns:
      - name: category_sk
        tests: [not_null, unique]
      - name: category_id
      - name: category_name

  - name: dim_seller
    description: "Seller dimension with surrogate key"
    columns:
      - name: seller_sk
        tests: [not_null, unique]
      - name: seller_username
      - name: seller_feedback_score
      - name: seller_feedback_percentage

  - name: dim_date
    description: "Date dimension with surrogate key"
    columns:
      - name: date_sk
        tests: [not_null, unique]
      - name: date
      - name: year
      - name: month
      - name: day
      - name: quarter
      - name: day_of_week

  - name: dim_image
    description: "Dimension table for item images"
    columns:
      - name: image_sk
        tests:
          - not_null
          - unique
      - name: image_url
        tests:
          - not_null

  - name: dim_shipping_option
    description: "Dimension table for shipping options"
    columns:
      - name: shipping_option_sk
        tests:
          - not_null
          - unique
      - name: shipping_cost_type
        tests:
          - not_null
      - name: shipping_currency
        tests:
          - not_null

  - name: dim_buying_option
    description: "Dimension table for buying options"
    columns:
      - name: buying_option_sk
        tests:
          - not_null
          - unique
      - name: buying_option
        tests:
          - not_null

  # BRIDGES
  - name: bridge_item_image
    description: "Bridge table linking item listings to images (many-to-many)"
    columns:
      - name: item_listing_sk
        tests:
          - not_null
          - relationships:
              to: ref('fact_item_listings')
              field: item_listing_sk
      - name: image_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_image')
              field: image_sk

  - name: bridge_item_shipping_option
    description: "Bridge table linking item listings to shipping options (many-to-many)"
    columns:
      - name: item_listing_sk
        tests:
          - not_null
          - relationships:
              to: ref('fact_item_listings')
              field: item_listing_sk
      - name: shipping_option_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_shipping_option')
              field: shipping_option_sk

  - name: bridge_item_buying_option
    description: "Bridge table linking item listings to buying options (many-to-many)"
    columns:
      - name: item_listing_sk
        tests:
          - not_null
          - relationships:
              to: ref('fact_item_listings')
              field: item_listing_sk
      - name: buying_option_sk
        tests:
          - not_null
          - relationships:
              to: ref('dim_buying_option')
              field: buying_option_sk
  #MARTS
  - name: mart_category_price_bands
    description: "Provides price distribution metrics per category for identifying investment opportunities"
    columns:
      - name: category_sk
        description: "Surrogate key for category"
        tests:
          - not_null
      - name: price_p25
        description: "25th percentile of price values"
      - name: price_median
        description: "50th percentile (median) of price values"
      - name: price_p75
        description: "75th percentile of price values"
      - name: avg_price
        description: "Average price in category"
      - name: price_stddev
        description: "Standard deviation of price in category"

  - name: mart_item_performance
    description: >
      Aggregated performance metrics for each item listing including price, coupon status,
      and priority listing flag to support business insights into listing effectiveness and pricing strategy.
    columns:
      - name: item_listing_sk
        description: Surrogate key for the item listing.
        tests:
          - not_null
          - unique
      - name: title
      - name: condition_sk
      - name: price_value
        description: Price of the item at the time of data capture.
        tests:
          - not_null
      - name: priority_listing
        tests:
          - accepted_values:
              values: [true, false]
      - name: top_rated_buying_experience
        description: Flag indicating if the item provides a top-rated buying experience.
        tests:
          - accepted_values:
              values: [true, false]
      - name: available_coupons
        description: Boolean flag indicating if coupons were available.
        tests:
          - accepted_values:
              values: [true, false]

      - name: shipping_cost
      - name: image_count
      - name: condition_id
      - name: listing_quality_score

  - name: mart_condition_price_index
    description: "Analyzes average and indexed price values by item condition"
    columns:
      - name: condition_sk
        description: "Surrogate key for condition"
        tests:
          - not_null
      - name: item_count
        description: "Number of items listed with this condition"
      - name: avg_price
        description: "Average price of items in this condition"
      - name: min_price
        description: "Minimum price"
      - name: max_price
        description: "Maximum price"
      - name: normalized_price_score
        description: "Standardized price score compared to other conditions"
