select
    item_id,
    title,
    try_parse_json(leaf_category_ids)[0] as category_id,
    try_parse_json(categories)[0]:categoryName as category_name,
    item_href,
    condition,
    condition_id,
    try_parse_json(thumbnail_images) as thumbnail_images,
    try_parse_json(shipping_options) as shipping_options,
    item_web_url,
    try_parse_json(additional_images) as additional_images,
    adult_only,
    legacy_item_id,
    available_coupons,
    item_origin_date,
    item_creation_date,
    top_rated_buying_experience,
    priority_listing,
    listing_marketplace_id,
    image_url,
    price_value,
    price_currency,
    seller_username,
    seller_feedback_percentage,
    seller_feedback_score,
    item_location_country,
    try_parse_json(buying_options) as buying_options,
    load_timestamp
from {{ source('ebay_raw_source','EBAY_RAW')}}
